# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
    types : [ "opened", "edited" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name : get_version
        run: echo command
  macos:
    name: macos
    runs-on: macos-latest
    steps:
      - name : get_version
        run:   sw_vers -productVersion
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name : get_version
        run: echo (Get-ItemProperty -Path c:\windows\system32\hal.dll).VersionInfo.FileVersion
      
